
all:	example2 example3 example4 example5

example2 : example2_source.c
	gcc -o example2 example2_source.c

example3 : example3_source.c
	gcc -o example3 example3_source.c

example4 : example4_source.c
	gcc -o example4 example4_source.c

example5 : example5_source.c
	gcc -o example5 example5_source.c

clean:
	rm example2 example3 example4 example5
